### ISSUE TITLE
Crash Error

### ISSUE THREAD

**Issue by ygtdmn** [tastybento/uablockconvert#3]
Hi when im trying to "uaconvert offline" server is crashing after a while. Especially after finish island convert.
It might be something related with island and player count. There are 149k islands ane 380k players. 10GB RAM, i7 4790K

Logs and crash report (3MB so i can't pastebin): http://www.mediafire.com/file/r2r9y92vu1c4321/2017-01-18-7.log.gz

**Comment by tastybento** [comment]
The conversion process is taking so long because you have so many to process that the server is timing out. Temporarily change the **timeout-time** in spigot.yml to something much larger, say 600 (5 minutes) so the process and complete. This is a just one-time thing you are doing, so this should not cause any problems. Put it back to your usual time afterwards.

**Comment by ygtdmn** [comment]
Solved problem. Thanks.
